### ISSUE TITLE
Resync feature not implemented

### ISSUE THREAD

**Issue by lbarman** [lbarman/prifi#14]
Branch: PriFi-SDA
Right now, client cannot join the protocol once it has started

**Comment by lbarman** [comment]
Resync should work in two layers (to be discussed if you have a different opinion)

Layer 1: after a long timeout (10 secs), any communication problem should be solved by killing all instances of prifi protocols, clients, etc. Every entity should basically restart from 0 and try to find eachothers (possibly ignoring a disconnected or buggy entity). This ensure that whatever happens (on the network, machines, human interaction), at least the prifi network does not remains stuck indefinitely when there exists entities that could run it.

This layer will rarely be used in practice, and can be very rough.

Layer 2: the "graceful" layer. Here, nodes try to warn before disconnecting, and (if that helps) the relays warns when he sees one node going offline. Using those messages, the protocol should be restarted much quicker. If possible, we should do the configuration of the new prifi protocol while keeping the old communication active. Example with clients A, B, C:

A,B,C connect to relay
begin setup phase with relay, trustees and A,B,C
begin communication phase with A,B,C
A wants to disconnect. He sends "A_ALL_GONNA_DISCONNECT". He *remains* connected
communication with A,B,C is still going on
begin setup phase 2 with nodes B,C
communication with A,B,C is still going on
when setup phase 2 is done:
begin communication phase B,C
kill communication phase A,B,C

If any step of this complex procedure goes wrong, we don't need to worry: Layer 1 will ensure that after a long timeout, nodes B and C will restart without A.

Note: we are *NOT* interested in *not loosing data* with this issue. We should worry first on the synchronisation, then on the socks5 parts where nodes do not lose data while resync'ing

**Comment by lbarman** [comment]
@Pamoi: please reach any stable point (that compiles and reasonnably works, probably without all features), then stop. We'll merge "sync" in "app-trustee" asap, it will be painful enough. I'll try to solve https://github.com/lbarman/prifi_dev/issues/31 and https://github.com/lbarman/prifi_dev/issues/32; when those three conditions are met, let's merge, then you can proceed with this.

**Comment by Pamoi** [comment]
I merged sync into app-trustee. The code is (hopefully) in a stable state where the protocol is restarted when a new node wishes to join but there is no handling of disconnections yet.

**Comment by lbarman** [comment]
Awesome. Did you (also) merge app-trustee into sync ? the point was to simplify the futur merge of sync in master or app-trustee.
Anyway, I let you go on, and i'll focus on the bugs. Thanks again

**Comment by Pamoi** [comment]
I just merged app-trustee into sync so we can continue working on it. I could not reproduce #32 after the merge, it may have been fixed with the relay taking care of starting the protocol at the right time.

**Comment by lbarman** [comment]
Done 142147b55c764a12657c5b14be7a20f3a39ba94b
