### ISSUE TITLE
Investigate time dependencies in the protocol

### ISSUE THREAD

**Issue by lbarman** [lbarman/prifi#2]
Pauses are used to make the output human-readable, but it bounds the number of clients joining and leaving the protocol, and at which rate.
TODO : Stress-test the configuration

**Comment by ineiti** [comment]
You can look at http://github.com/dedis/cothority/lib/debug_lvl which is a small library that let's you use different debug-levels to show different details of debugging. We use it in the cothority-code to mark things we want to show always (level1), things for a bit more detail (level2), debugging output (level3), more debugging output (level4) and printing large structures (level5). Usually it runs in level1, so we only see the most important. Level2 is only used for snooping around, aso.

We also have a 'monitor'-library that is very nice to measure things like round-times, verification-times, aso. This is in http://github.com/dedis/cothority/lib/monitor.

At least debug_lvl is usable standalone, monitor needs perhaps some hand-holding to be used separate.

**Comment by lbarman** [comment]
Thanks a lot for the resources ! 
I don't think I need the network part of "monitor", especially since I need to measure the time spend in each state of a state machine, but I'll gladly copy a bit of stats.go ;)
For now, everything is logged on the same level, this could be improved as well indeed. Thanks for pointing that out.

**Comment by lbarman** [comment]
Done c79fae7e06730a95454374fdb893560d1a9f5e0a
