### ISSUE TITLE
Protocol does not work if some clients with a lower id than the highest one are not connected

### ISSUE THREAD

**Issue by Pamoi** [lbarman/prifi#34]
Fixing this will probably need changes in prifi-lib.

**Comment by lbarman** [comment]
In fact, "ids" should be decided by the relay, every time there is a change in the client list, and a priori clients should not "tell their ID".
It might make sense to have a "config_id" when you run the client (to fetch the correct key in cothority), and a "runtime_id" that gets assigned by the relay
